### ISSUE TITLE
Configuring sign highlight groups

### ISSUE THREAD

**Issue by noahfrederick** [pgdouyon/vim-accio#32]
I'm on a campaign against global variables for configuration :smile:. Would you accept a patch to effectively change this:

``` vim
let g:accio_error_highlight = get(g:, "accio_error_highlight", "Error")
let g:accio_warning_highlight = get(g:, "accio_warning_highlight", "Search")

execute "sign define AccioError text=>> texthl=".g:accio_error_highlight
execute "sign define AccioWarning text=>> texthl=".g:accio_warning_highlight
```

Into this:

``` vim
sign define AccioError text=>> texthl=AccioErrorSign
sign define AccioWarning text=>> texthl=AccioWarningSign

highlight default link AccioErrorSign Error
highlight default link AccioWarningSign Search
```

?

This way, a user or color scheme could change the appearance in the more usual way:

``` vim
highlight! link AccioErrorSign ErrorMsg
" or
highlight AccioErrorSign guifg=#ff2200 ctermfg=1
```

I'm also not convinced that `Search` is an appropriate default for the warning highlight group. How about a default of `WarningMsg` (and `ErrorMsg` for symmetry)?

**Comment by pgdouyon** [comment]
Yea this is a great idea, those two variables in particular have really been bothering me since you can't change them in the middle of a Vim session, you have to restart Vim or re-source the plugin file.

I went with `Search` as the warning default because most colorschemes had a yellow background for the `Search` highlight group or something similarly eye-catching which seemed appropriate.  But I agree that the semantics of using `Search` in this way are dodgy and `WarningMsg` would be a better default.
